#pragma once

#define RUN_SIM_ENGINE
#define RUN_TRANSFORM
#define RUN_RENDERER

#define DISPLAY_COLORS

#define OFF_SCREEN_RENDERING

#define RENDER_WINDOW_HEIGHT (480 * 2)
#define RENDER_WINDOW_WIDTH (640 * 2)
